CREATE DATABASE IF NOT EXISTS rosdb DEFAULT CHARACTER SET utf8mb4;

USE rosdb;

-- 거북이 위치 데이터 테이블
CREATE TABLE IF NOT EXISTS turtlepos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  theta FLOAT NOT NULL,
  time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);